In [ ]:
#!pip install tensorflow
#!pip install git+https://github.com/twolodzko/tfmf.git

In [1]:
import numpy as np
from tfmf import MatrixFactorizer, sparse_matrix

from scipy.sparse import coo_matrix

user_id = [0,0,1,1,2,2]
movie_id = [0,1,2,0,1,2]
rating = [1,1,2,2,3,3]
X = sparse_matrix(user_id, movie_id, rating)

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
import tensorflow as tf
dir(tf)

In [8]:
print(X.todense())

[[1 1 0]
 [2 0 2]
 [0 3 3]]


In [28]:
np.random.seed(0)
m = 1000
n = 10
k = 2
A = np.random.rand(m, k).dot(np.random.rand(k, n))
tmp = np.random.choice(range(m*n), int(0.2*m*n),replace=False)
Anew = A.copy()
Anew[tmp//n, tmp % n] = np.nan
Anew = np.nan_to_num(Anew)


Anew = coo_matrix(Anew)
Anew.eliminate_zeros()
Anew = Anew.todok()

In [33]:
mf = MatrixFactorizer(n_components=k, batch_size=4, implicit=False, n_iter=10000)
mf.fit(Anew)
mf.predict_all().A

100%|██████████| 10000/10000 [00:12<00:00, 781.01it/s]


array([[0.70331466, 0.4293582 , 0.48507717, ..., 0.5790831 , 0.40193182,
        0.788309  ],
       [0.5972949 , 0.32333842, 0.37905738, ..., 0.47306326, 0.29591203,
        0.68228924],
       [0.627645  , 0.35368854, 0.4094075 , ..., 0.5034134 , 0.32626215,
        0.71263933],
       ...,
       [0.61774415, 0.34378764, 0.3995066 , ..., 0.4935125 , 0.31636125,
        0.7027384 ],
       [0.83773416, 0.5637777 , 0.61949664, ..., 0.7135025 , 0.5363513 ,
        0.9227285 ],
       [0.6685742 , 0.3946176 , 0.450337  , ..., 0.54434234, 0.36719126,
        0.75356865]], dtype=float32)

In [29]:
Anew.todense()

matrix([[0.75062907, 0.45303022, 0.38123174, ..., 0.61252311, 0.42714198,
         0.87543909],
        [0.72172039, 0.43305422, 0.38704418, ..., 0.4979935 , 0.        ,
         0.74397234],
        [0.61948391, 0.37486546, 0.30663518, ..., 0.        , 0.37427668,
         0.76059775],
        ...,
        [0.67405921, 0.40945763, 0.32094634, ..., 0.64498412, 0.        ,
         0.        ],
        [0.79018497, 0.47207222, 0.44047979, ..., 0.47104661, 0.34299842,
         0.73480292],
        [0.73667412, 0.44106338, 0.        , ..., 0.473659  , 0.34095427,
         0.72213886]])

In [34]:
A

array([[0.75062907, 0.45303022, 0.38123174, ..., 0.61252311, 0.42714198,
        0.87543909],
       [0.72172039, 0.43305422, 0.38704418, ..., 0.4979935 , 0.35487173,
        0.74397234],
       [0.61948391, 0.37486546, 0.30663518, ..., 0.54096121, 0.37427668,
        0.76059775],
       ...,
       [0.67405921, 0.40945763, 0.32094634, ..., 0.64498412, 0.44184741,
        0.88819207],
       [0.79018497, 0.47207222, 0.44047979, ..., 0.47104661, 0.34299842,
        0.73480292],
       [0.73667412, 0.44106338, 0.40287309, ..., 0.473659  , 0.34095427,
        0.72213886]])